services:

  aituber:
    environment:
      - NEXT_PUBLIC_CUSTOM_API_URL=https://flutter-generated-app.unolive.tech/api/chat

  voicevox:
    environment:
      - VV_CPU_NUM_THREADS=16

  orchestrator:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - aituber
      - orchestrator
    networks:
      - app-net
